name: Deploy Dashboard

on:
  push:
    branches:
      - main # Only run on commits to the main branch

jobs:
  deploy_dashboard:
    runs-on: self-hosted # Use the self-hosted runner (on your EC2 instance)

    steps:
      # Checkout the latest code on the runner (this step clones the repo to the EC2 runner)
      - name: Checkout Code
        uses: actions/checkout@v2

      # Remove existing dist folder on EC2 before copying new one
      - name: Remove Old Dist Files from EC2
        run: |
          rm -rf /var/www/html/*

      # Copy the local dist files from the GitHub runner (EC2) to the web server directory
      - name: Copy Dashboard Build Files to EC2
        run: |
          cp -r dist/* /var/www/html/

      # Restart Nginx to reflect the new changes
      - name: Restart Nginx
        run: |
          sudo systemctl restart nginx
