name: Deploy YHAM

on:
  push:
    branches:
      - main # Only run on commits to the main branch

jobs:
  deploy_dashboard:
    runs-on: self-hosted # Use the self-hosted runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          echo "${{ secrets.SSH_KEY_DASBOARD }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST_DASHBOARD }} >> ~/.ssh/known_hosts

      - name: Copy Dashboard Build Files to EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST_DASHBOARD }}
        run: |
          # Copy dist folder to the EC2 instance for the dashboard
          scp -r dist/* $EC2_USER@$EC2_HOST:/var/www/html/

      - name: Restart Nginx
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST_DASHBOARD }}
        run: |
          ssh $EC2_USER@$EC2_HOST "sudo systemctl restart nginx"
